<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<script>
$(document).ready(function($){
  $("#myInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    //alert(indexOf(value));
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>

<body>

<h2>Filterable Table for Women's Top</h2>
<p>Type something in the input field to search the women's top:</p>  
<input id="myInput" type="text" placeholder="Search..">
<br><br>
<table>
  <thead>
  <tr>
    <th>Product Name</th>
    <th>Price</th>
    <th>SKU</th>
  </tr>
  </thead>

<?php
$categoryId = 21; // fetching products in category id 6
$categoryProducts = $block->getCategoryProducts($categoryId);

foreach ($categoryProducts as $product) {
	//$productId = $product->getId();
	//echo $productId; 
	//$image = $block->getProductImageUsingCode($productId);
	//var_dump($image);
    ?>
    <tbody id="myTable"><tr>
    	<td><a href="<?php echo $product->getProductUrl() ?>"><?php echo $product->getName(); ?></a></td>
    	<td><?php echo '$'.$product->getFinalPrice(); ?></td>
    	<td><?php echo $product->getSku(); ?></td>
    </tr></tbody>
  
  <?php
}
?>
</table>
</body>
</html>
